#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/MemberDB?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: dkfkqldk12~
#
#mybatis:
#  config: mybatis-config.xml
#  type-aliases-package: com.example.demo.model
#  mapper-locations: mybatis/mapper/*.xml

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
